### ISSUE TITLE
travis.yml `import` option

### ISSUE THREAD

**Issue by coreyfarrell** [sindresorhus/meta#13]
Just wanted to let you know travis has added (beta) support for an `import` option - https://docs.travis-ci.com/user/build-config-imports/.

The way this would look for your repositories would be something like:
```yml
version: ~> 1.0
import:
  - sindresorhus/travis-ci:node-active.yml
```

This assumes you create a `github.com/sindresorhus/travis-ci` repository containing a `node-active.yml` in the master branch:
```yml
language: node_js
node_js:
  - '13'
  - '12'
  - '10'
  - '8'
```

One thing not mentioned in the travis-ci docs this doesn't work if travis-ci is unaware of the repository you are importing from.  When I set this up for some of my personal projects I had to click the 'Sync Account' button on Travis so it could see the shared configs repository I had just created.

Feel free to just close this issue, I just figured with the number of repos you manage this could be useful to you.
